/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetooperacoesbancarias;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jereelton
 */
public class TelaContaCorrente extends javax.swing.JFrame {

    OperaContaCorrente operacaoConta = new OperaContaCorrente();
    FormataMoeda        formataMoeda = new FormataMoeda();
    
    /**
     * Creates new form TelaInterativa
     */
    public TelaContaCorrente() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        depositarJTextField = new javax.swing.JTextField();
        depositarJButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        resgatarJTextField = new javax.swing.JTextField();
        resgatarJButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        extratoJTable = new javax.swing.JTable();
        extratoJButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        saldoJTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela Conta Corrente");
        setMaximumSize(new java.awt.Dimension(510, 570));
        setMinimumSize(new java.awt.Dimension(510, 570));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));
        jPanel1.setMaximumSize(new java.awt.Dimension(500, 80));
        jPanel1.setMinimumSize(new java.awt.Dimension(500, 80));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 80));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Depósitos");

        depositarJTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        depositarJTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        depositarJTextField.setMaximumSize(new java.awt.Dimension(200, 30));
        depositarJTextField.setMinimumSize(new java.awt.Dimension(200, 30));
        depositarJTextField.setPreferredSize(new java.awt.Dimension(200, 30));
        depositarJTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                depositarJTextFieldKeyReleased(evt);
            }
        });

        depositarJButton.setText("Depositar");
        depositarJButton.setMaximumSize(new java.awt.Dimension(100, 30));
        depositarJButton.setMinimumSize(new java.awt.Dimension(100, 30));
        depositarJButton.setPreferredSize(new java.awt.Dimension(100, 30));
        depositarJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositarJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(depositarJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(depositarJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(depositarJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(depositarJButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 16, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setMaximumSize(new java.awt.Dimension(500, 80));
        jPanel2.setMinimumSize(new java.awt.Dimension(500, 80));
        jPanel2.setPreferredSize(new java.awt.Dimension(500, 80));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Resgates");

        resgatarJTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        resgatarJTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        resgatarJTextField.setMaximumSize(new java.awt.Dimension(200, 30));
        resgatarJTextField.setMinimumSize(new java.awt.Dimension(200, 30));
        resgatarJTextField.setPreferredSize(new java.awt.Dimension(200, 30));
        resgatarJTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                resgatarJTextFieldKeyReleased(evt);
            }
        });

        resgatarJButton.setText("Resgatar");
        resgatarJButton.setMaximumSize(new java.awt.Dimension(100, 30));
        resgatarJButton.setMinimumSize(new java.awt.Dimension(100, 30));
        resgatarJButton.setPreferredSize(new java.awt.Dimension(100, 30));
        resgatarJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resgatarJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(resgatarJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(resgatarJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(resgatarJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resgatarJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 21, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setMaximumSize(new java.awt.Dimension(500, 300));
        jPanel3.setMinimumSize(new java.awt.Dimension(500, 300));
        jPanel3.setPreferredSize(new java.awt.Dimension(500, 300));

        extratoJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Operação", "Valor", "Saldo"
            }
        ));
        extratoJTable.setEnabled(false);
        extratoJTable.setFocusable(false);
        extratoJTable.setMaximumSize(new java.awt.Dimension(480, 242));
        extratoJTable.setMinimumSize(new java.awt.Dimension(480, 242));
        extratoJTable.setPreferredSize(new java.awt.Dimension(480, 242));
        extratoJTable.setRequestFocusEnabled(false);
        extratoJTable.setRowSelectionAllowed(false);
        extratoJTable.setUpdateSelectionOnSort(false);
        extratoJTable.setVerifyInputWhenFocusTarget(false);
        jScrollPane1.setViewportView(extratoJTable);

        extratoJButton.setText("Extrato");
        extratoJButton.setMaximumSize(new java.awt.Dimension(100, 30));
        extratoJButton.setMinimumSize(new java.awt.Dimension(100, 30));
        extratoJButton.setPreferredSize(new java.awt.Dimension(100, 30));
        extratoJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                extratoJButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Histórico de operações da conta");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(extratoJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(extratoJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setMaximumSize(new java.awt.Dimension(500, 71));
        jPanel4.setMinimumSize(new java.awt.Dimension(500, 71));
        jPanel4.setPreferredSize(new java.awt.Dimension(500, 71));

        saldoJTextField.setEditable(false);
        saldoJTextField.setBackground(new java.awt.Color(255, 255, 255));
        saldoJTextField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        saldoJTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        saldoJTextField.setMaximumSize(new java.awt.Dimension(200, 30));
        saldoJTextField.setMinimumSize(new java.awt.Dimension(200, 30));
        saldoJTextField.setPreferredSize(new java.awt.Dimension(200, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 255, 153));
        jLabel4.setText("SALDO CONTA");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(saldoJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saldoJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void depositarJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositarJButtonActionPerformed
        
        String valorInserir = depositarJTextField.getText();
        operacaoConta.depositarValor(valorInserir);
        saldoJTextField.setText(operacaoConta.retornarSaldoConta() );
        depositarJTextField.setText("");
        resgatarJTextField.setText("");
        
    }//GEN-LAST:event_depositarJButtonActionPerformed

    private void resgatarJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resgatarJButtonActionPerformed
        
        String valorRemover = resgatarJTextField.getText();
        operacaoConta.resgatarValor(valorRemover);
        saldoJTextField.setText(operacaoConta.retornarSaldoConta() );
        depositarJTextField.setText("");
        resgatarJTextField.setText("");
        
    }//GEN-LAST:event_resgatarJButtonActionPerformed

    private void extratoJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_extratoJButtonActionPerformed
        
        ArrayList<String> extratoConta = operacaoConta.retornarExtratoConta();
        DefaultTableModel modeloTabela = new javax.swing.table.DefaultTableModel();
        
        modeloTabela.addColumn("Operação");
        modeloTabela.addColumn("Valor");
        modeloTabela.addColumn("Saldo");
        
        for (String extratoContaLoop : extratoConta) {
            
            operacaoConta.configurarExtratoConta(extratoContaLoop);
            
            modeloTabela.addRow(new String[]{
                operacaoConta.tipoOperacaoConta(),
                operacaoConta.valorOperacaoConta(),
                operacaoConta.saldoOperacaoConta()
            });
            
        }
        
        extratoJTable.setModel(modeloTabela);
        
    }//GEN-LAST:event_extratoJButtonActionPerformed

    private void depositarJTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_depositarJTextFieldKeyReleased
        
        depositarJTextField.setText(this.formataMoeda.formatar(depositarJTextField.getText()));
        
    }//GEN-LAST:event_depositarJTextFieldKeyReleased

    private void resgatarJTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_resgatarJTextFieldKeyReleased
        
        resgatarJTextField.setText(this.formataMoeda.formatar(resgatarJTextField.getText()));
        
    }//GEN-LAST:event_resgatarJTextFieldKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaContaCorrente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaContaCorrente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaContaCorrente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaContaCorrente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaContaCorrente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton depositarJButton;
    private javax.swing.JTextField depositarJTextField;
    private javax.swing.JButton extratoJButton;
    private javax.swing.JTable extratoJTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton resgatarJButton;
    private javax.swing.JTextField resgatarJTextField;
    private javax.swing.JTextField saldoJTextField;
    // End of variables declaration//GEN-END:variables
}
